### ISSUE TITLE
chaduke - The useOffer() function fails to enforce the constraint of BorrowAmountPerOfferLowerBound.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#111]
chaduke

medium

# The useOffer() function fails to enforce the constraint of BorrowAmountPerOfferLowerBound.

## Summary
The useOffer() function fails to enforce the constraint of BorrowAmountPerOfferLowerBound.

## Vulnerability Detail
The setBorrowAmountPerOfferLowerBound() function is used to set the constraint of lower bound for borrowed amount fro each offer for a particular ERC20 tokens:

[https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L72-L75](https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L72-L75)

However, this constraint is never enforced in the function ``useOffer()``:

[https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L28-L93](https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L28-L93)

As a result, a borrower might borrow from an offer with an amount small than the ``BorrowAmountPerOfferLowerBound``. 

## Impact

setBorrowAmountPerOfferLowerBound() sets the constraint of BorrowAmountPerOfferLowerBound, but it can be violated by ``userOffer()``.

## Tool used
VScode

Manual Review

## Recommendation
Enforce the constraint in ``userOffer()``.

**Comment by npasquie** [comment]
the constraint is enforced here https://github.com/kairos-loan/kairos-contracts/blob/ce49230ab5255662d287c4944229cf411725de3f/src/BorrowLogic/BorrowCheckers.sol#L37-L39
