### ISSUE TITLE
chaduke - The repay() function fails to enforce the MinOfferCost constraint.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#112]
chaduke

medium

# The repay() function fails to enforce the MinOfferCost constraint.

## Summary
The repay() function fails to enforce the MinOfferCost() constraint.

## Vulnerability Detail

The ``setMinOfferCost()`` sets the constraint for the new minimum amount that will need to be repaid per loan offer used:

[https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L64-L67](https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L64-L67)

However, this constraint is never enforced by the ``repay()`` function:

[https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/RepayFacet.sol#L24-L61](https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/RepayFacet.sol#L24-L61)

As a result, the MinOfferCost constraint might be violated. 

## Impact

The repay() function fails to enforce the MinOfferCost constraint.

## Tool used
VScode

Manual Review

## Recommendation
Enforce the constraint of MinOfferCost constraint in repay().

**Comment by npasquie** [comment]
this constraint is enforced by this calculus https://github.com/kairos-loan/kairos-contracts/blob/ce49230ab5255662d287c4944229cf411725de3f/src/RepayFacet.sol#L40-L53
through the `minInterestsToRepay` value stored at borrow time
