### ISSUE TITLE
0Kage - Naive lender making an offer in a ERC20 asset not approved by Kairos governance can face a DDOS attack from malicious borrower

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#128]
0Kage

medium

# Naive lender making an offer in a ERC20 asset not approved by Kairos governance can face a DDOS attack from malicious borrower

## Summary
If a lender makes an offer in a ERC20 asset that is not approved by Kairos governance, a malicious borrower can execute a DDOS attack by creating a potentially unlimited number of supply position NFT's.

This is possible because the minimum repay amount and minimum borrow amount per offer would be 0 for such unapproved ERC20 asset. While current implementation protects lenders lending approved ERC20 assets from DDOS attacks, there is no protection for unapproved assets. Current implementation does not check if offered asset has minimum repay amount & minimum borrow amount set by governance before using that offer for loan creation. Dust attack can prevent lenders from claiming their dues & hence cause them losses

## Vulnerability Detail
[AdminFacet](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/AdminFacet.sol#L72) allows protocol owner to set minimum amount to repay (`setMinOfferCost`) and minimum borrow amount per offer (`setBorrowAmountPerOfferLowerBound`) for a given ERC20 asset.

When borrower chooses select offers to create a loan against her NFT collateral, [`useOffer` in BorrowHandlers](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/BorrowLogic/BorrowHandlers.sol#L32) checks the offer details by calling `checkOfferArg` function.

[`checkOfferArg` in BorrowCheckers](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/BorrowLogic/BorrowCheckers.sol#L23) checks if the same ERC20 asset & same interest rate is used across all offers. However, there is no check to validate if ERC20 asset has a minimum amount to repay or minimum borrow amount set by the protocol governance. Not checking if these values are non-zero opens the attack vector for DDOS attack.

## Impact
Lender will have to spend a huge gas cost to claim interest by burning token IDs created by dust attack. This can result in losses to lenders

While protocol is protecting users who make offers in select assets, it is not preventing lenders from DDOS attacks for other assets. 

## Code Snippet
https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/AdminFacet.sol#L72

https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/BorrowLogic/BorrowHandlers.sol#L32

https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/BorrowLogic/BorrowCheckers.sol#L23

## Tool used
Manual Review

## Recommendation
Consider adding following check in the [`checkOfferArg`](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/BorrowLogic/BorrowCheckers.sol#L23) function

```solidity
  function checkOfferArg(OfferArg memory arg) internal view returns (address signer) {

    ...
    if(proto.offerBorrowAmountLowerBound[arg.offer.assetToLend] == 0
    && proto.minOfferCost[arg.offer.assetToLend] == 0
    ){
        revert UnrecognisedLendgingAsset(); //@audit -> revert if both are 0
    }
    ...
    }

```

**Comment by npasquie** [comment]
this issue was mentioned in the contest readme as known and invalid as finding
