### ISSUE TITLE
boredpukar - Reentrancy issue with checkLoanStatus function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#13]
boredpukar

medium

# Reentrancy issue with checkLoanStatus function

## Summary

Reentrancy Issues in implementation of checkLoanStatus

## Vulnerability Detail

The checkLoanStatus function only checks if the loan has already been paid or liquidated, but it does not verify that the loan's collateral has been transferred to the contract, leaving room for potential attacks that bypass this check.

An attacker can manipulate the value of `loan.payment.paid` or `loan.payment.liquidated` through a malicious Loan struct, causing the `useLoan` function to revert and perform a reentrancy attack.

They can create a Loan struct with `payment.liquidated` set to true and `payment.paid` set to some arbitrary non-zero value. Then they could bypass the LoanAlreadyRepaid check in checkLoanStatus and cause the useLoan function to execute the following code block:

`loan.assetLent.checkedTransferFrom(msg.sender, address(this), toPay);`
`loan.collateral.implem.safeTransferFrom(address(this), arg.to, loan.collateral.id);`

If the safeTransferFrom function call triggers a callback to an external contract, the attacker could potentially re-enter the useLoan function and execute additional code before the transfer is completed, resulting in a reentrancy attack.

## Impact

Ability to cause a potential reentrancy attack 

## Code Snippet

[Reference One](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/AuctionFacet.sol#L39)

[Reference Two](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/AuctionFacet.sol#L77)

[Use Loan and Check Loan Status](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/AuctionFacet.sol#L59-L86

## Tool used

Manual Review

## Recommendation

Use robust mechanism for managing the state of the Loan struct, such as a separate LoanRegistry contract, which can not be easily manipulated.

**Comment by npasquie** [comment]
Users can't store arbitrary loan struct to storage
