### ISSUE TITLE
0Kage - A borrower with multiple loans of which one is liquidated can withdraw much more than his share of liquidation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#130]
0Kage

high

# A borrower with multiple loans of which one is liquidated can withdraw much more than his share of liquidation

## Summary
A borrower with multiple loans can call [`claimAsBorrower` in ClaimFacet](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/ClaimFacet.sol#L58) to claim all his outstanding share in collateral liquidated.

If a loan is liquidated, balance share is calculated and sent to the borrower. However, the sent amount is not reset to 0 & is again used for the next `loanID`. As a result, a borrower can withdraw several times over causing a loss to lenders

## Vulnerability Detail
[`claimAsBorrower` in ClaimFacet](https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/ClaimFacet.sol#L58) is running a loop over all loanIds. If a loan is liquidated, `sentTemp` is calculated as a balance remaining after paying the share to lenders. If `sentTemp` is greater than 0, Kairos contract transfers the amount to borrower.

```solidity
  for (uint256 i = 0; i < loanIds.length; i++) {
            loanId = loanIds[i];
            loan = proto.loan[loanId];
            if (loan.borrower != msg.sender) {
                revert NotBorrowerOfTheLoan(loanId);
            }
            if (loan.payment.borrowerClaimed) {
                revert BorrowerAlreadyClaimed(loanId);
            }
            if (loan.payment.liquidated) {
                loan.payment.borrowerClaimed = true;
                // 1 - shareLent = share belonging to the borrower (not used as collateral)
                sentTemp = loan.payment.paid.mul(ONE.sub(loan.shareLent));
            } else {
                revert LoanNotRepaidOrLiquidatedYet(loanId);
            }
            if (sentTemp > 0) {
                /* the function may be called to store that the borrower claimed its due, but if this due is of 0 there
                is no point in emitting a transfer and claim event */
                loan.assetLent.checkedTransfer(msg.sender, sentTemp);
                sent += sentTemp;
                emit Claim(msg.sender, sentTemp, loanId);
            }
        }
```

However, note that `sentTemp` is not reset back to 0 before the loop runs with the next loan - since `sentTemp` > 0, a duplicate transfer is again made to the borrower. 

If a borrower stacks the array of `loanIDs` such that the first `loanID` corresponds to a liquidated loan, borrower will get paid the liquidation share as many times as there are number of loans. This is free money for borrower at the expense of lenders.

## Impact
Direct loss to lenders as the payouts will be made from the lenders unclaimed income.

## Code Snippet
https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/ClaimFacet.sol#L58

## Tool used
Manual Review

## Recommendation
Reset `sentTemp` back to 0 after making the transfer.

**Comment by npasquie** [comment]
thx to the lead judge for pointing a flaw in the report
`sentTemp` will always have a new value reassigned on line 76 https://github.com/kairos-loan/kairos-contracts/blob/b2fd98d62cf0f25ee1db2bd551cd7b4606a5a988/src/ClaimFacet.sol#L76
or revert due to check of line 73
so no transfer will happen with an amount not calculated from current liquidated loan
