### ISSUE TITLE
gryphon - Buyer may not be able to liquidate the loan

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#161]
gryphon

medium

# Buyer may not be able to liquidate the loan

# Buyer may not be able to liquidate the loan

## Summary

The `buy` function of the contract `AuctionFacet.sol` calls the function `useLoan`, which then, calls `checkedTransferFrom`, which will call the ERC20 `transferFrom` to transfer the funds from the `msg.sender` to the Kairos contract `address(this)`, with the intention to buy the NFT. But the `ERC20` `transferFrom` function, requires funds to be previously `approved`, which is not checked.  See details below.

## Vulnerability Detail
The external function `buy` calls the function `useLoan`, which calls `checkedTransferFrom`. As the library `Erc20CheckedTransfer` is being used for `IERC20` tokens, the function above will be called.
```solidity=
    using Erc20CheckedTransfer for IERC20;
    ...
    function buy(BuyArg[] memory args) external {
        for (uint256 i = 0; i < args.length; i++) {
            useLoan(args[i]);
        }
    }

function useLoan(BuyArg memory arg) internal {    ... 
    loan.assetLent.checkedTransferFrom(msg.sender, address(this), toPay);
    ...
    }
```

The function `checkedTransferFrom` from the library `Erc20CheckedTransfer` will call the `ERC20` `transferFrom` function. This `msg.sender` above is passed as a parameter and becomes the `from` in the function below:

```solidity=
    function checkedTransferFrom(IERC20 currency, address from, address to, uint256 amount) internal {
        if (!currency.transferFrom(from, to, amount)) {
            revert ERC20TransferFailed(currency, from, to);
        }
    }
```

which requires funds to be previously approved, as we can see on the OZ `ERC20` implementation (now, the `from` parameter is the one who owns the tokens):

```solidity=
    function transferFrom(address from, address to, uint256 amount) public virtual override returns (bool) {
        address spender = _msgSender();
        _spendAllowance(from, spender, amount);
        _transfer(from, to, amount);
        return true;
    }
```

The code snipet above, from OZ `ERC20` implementation, calls the function `_spendAllowance`, which checks if `msg.sender`, the `spender` is approved to spend on behalf of the `from` (which owns the tokens). The `msg.sender` now is the Kairos contract who is trying to spend on behalf of the `from`.

```solidity=
    function _spendAllowance(address owner, address spender, uint256 amount) internal virtual {
        uint256 currentAllowance = allowance(owner, spender);
        if (currentAllowance != type(uint256).max) {
            require(currentAllowance >= amount, "ERC20: insufficient allowance");
            unchecked {
                _approve(owner, spender, currentAllowance - amount);
            }
        }
    }
```
As we can see above, the `spender` needs to be approved to spend on behalf of the `owner` (the `from` parameter on the previous call).

As it stated by the first comment above (before the `repay` function), and on the Kairos documentation, anyone is allowed to pay a loan to a borrower. Then it is important to check if the payer allowed Kairos contract to spend the `ERC20` tokens on behalf of him.

The `EPI20` specs also states the needing for that chack  

[eip-20#methods](`https://eips.ethereum.org/EIPS/eip-20#methods`)

`The function SHOULD throw unless the _from account has deliberately authorized the sender of the message via some mechanism.`

The transaction will fail and the buyer will not be properly informed about the error.

## Impact

Buyer may not be able to buy NFT in Auction. Buyer could not be properly informed about the need to approve the amount first and the loan could not be liquidated.

## Code Snippet

[AuctionFacet.sol#L69](`https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AuctionFacet.sol#L69`)

```solidity=
    function useLoan(BuyArg memory arg) internal {    ... 
          loan.assetLent.checkedTransferFrom(msg.sender, address(this), toPay);
    ...
    }
```

## Tool used

Manual Review

## Recommendation

Consider checking for the approval, before calling the `transferFrom`. Add an check for the approval and, if not enough amount, call approve, on the file `Erc20CheckedTransfer.sol`:

[Erc20CheckedTransfer.sol#L9](`https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/utils/Erc20CheckedTransfer.sol#L9`)

```solidity=
    function checkedTransferFrom(IERC20 currency, address from, address to, uint256 amount) internal {
+       if(currency.allowance(from,address(this))<amount){
+           if(!currency.approve(address(this),amount)){
+                revert ERC20TransferNotAllowed(currency, from, to);
+            }
+       }
        if (!currency.transferFrom(from, to, amount)) {
            revert ERC20TransferFailed(currency, from, to);
        }
    }
    ...
    } 
```

[Errors.sol#L10](`https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/DataStructure/Errors.sol#L10`)

Add an `error` on the `Errors.sol`:
`error ERC20TransferNotAllowed(IERC20 token, address from, address to);`

```solidity=
...
    error ERC20TransferFailed(IERC20 token, address from, address to);
+   error ERC20TransferNotAllowed(IERC20 token, address from, address to);
...
```

**Comment by npasquie** [comment]
I don't consider this issue valid, as it is normal and usual procedure in DeFi for the caller to approve its tokens to a contract when it will spend them. Also, this does not blocks any asset in the contract, the buyer just need to approve first
