### ISSUE TITLE
jekapi - Loan can be repaid even after `loan.endDate`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#22]
jekapi

medium

# Loan can be repaid even after `loan.endDate`

## Summary
The function `repay` doesn't check that a loan's end date hasn't past even though documentation indicates loan can't be repaid after that date.

## Vulnerability Detail
The function `repay` can be called after an auction for the collateral has started, i.e. after `loan.endDate` which is defined in the following manner:

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/DataStructure/Storage.sol#L42
```solidity
/// @param endDate timestamp after which sale starts & repay is impossible
```

This will set `loan.payment.paid` to a non-zero amount and cause all transactions of auction participants to revert due to the check in the function `checkLoanStatus`:

```solidity
if (loan.payment.paid != 0 || loan.payment.liquidated) {
    revert LoanAlreadyRepaid(loanId);
}
```

## Impact
A borrower can front-run liquidation attempts for his collateral causing loss of gas for auction participants and potentially breaking transactions attempting to buy multiple auctioned NFTs (which were used as collateral).

## Code Snippet
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/RepayFacet.sol#L32-L59
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AuctionFacet.sol#L83

## Tool used
Manual Review

## Recommendation
Add the following check in the function repay `repay`:
```solidity
if (block.timestamp >= loan.endDate) {
    revert LoanRepayAttemptDuringAuction(loanId); // TODO: implement this error.
}
```

**Comment by npasquie** [comment]
The ability to repay during liquidation time is intended in a similar fashion as a grave period
