### ISSUE TITLE
p0wd3r - In certain situations, the lender will gain nothing.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#28]
p0wd3r

high

# In certain situations, the lender will gain nothing.

## Summary
When the auction price reaches 0, if the attacker liquidates through `buy` before the lender, he will obtain the collateralized NFT and the lender will receive nothing.
## Vulnerability Detail

In the `useLoan` function, `toPay` can be 0 due to the `decreasingFactor`, so liquidators can obtain the NFT without paying any fees.
https://github.com/kairos-loan/kairos-contracts/blob/main/src/AuctionFacet.sol#L43
https://github.com/kairos-loan/kairos-contracts/blob/main/src/AuctionFacet.sol#L59
```solidity
function useLoan(BuyArg memory arg) internal {
        Loan storage loan = protocolStorage().loan[arg.loanId];

        checkLoanStatus(arg.loanId);
        uint256 toPay = price(arg.loanId);

        /* store as liquidated and paid before transfers to avoid malicious reentrency, following
        checks-effects-interaction pattern */
        loan.payment.liquidated = true;
        loan.payment.paid = toPay;
        loan.assetLent.checkedTransferFrom(msg.sender, address(this), toPay);
        loan.collateral.implem.safeTransferFrom(address(this), arg.to, loan.collateral.id);

        emit Buy(arg.loanId, abi.encode(arg));
}
```

Although this is expected in the document, it does not benefit the protocol and lender. The revenue of the protocol has not increased, and lenders have also lost the opportunity to obtain NFTs and wait for them to appreciate again.

## Impact
Lenders will lose the opportunity to obtain NFTs and wait for them to appreciate again.
## Code Snippet
https://github.com/kairos-loan/kairos-contracts/blob/main/src/AuctionFacet.sol#L43
https://github.com/kairos-loan/kairos-contracts/blob/main/src/AuctionFacet.sol#L59
```solidity
function useLoan(BuyArg memory arg) internal {
        Loan storage loan = protocolStorage().loan[arg.loanId];

        checkLoanStatus(arg.loanId);
        uint256 toPay = price(arg.loanId);

        /* store as liquidated and paid before transfers to avoid malicious reentrency, following
        checks-effects-interaction pattern */
        loan.payment.liquidated = true;
        loan.payment.paid = toPay;
        loan.assetLent.checkedTransferFrom(msg.sender, address(this), toPay);
        loan.collateral.implem.safeTransferFrom(address(this), arg.to, loan.collateral.id);

        emit Buy(arg.loanId, abi.encode(arg));
}
```
## Tool used

Manual Review

## Recommendation
After the auction price becomes 0, only the lender is allowed to liquidate.

**Comment by npasquie** [comment]
I disagree there is a problem in letting anyone claim an NFT from which the protocol could extract no value
