### ISSUE TITLE
Koolex - offerBorrowAmountLowerBound (alone) doesn't mitigate the ddos risk for all ERC20 tokens effectively

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#38]
Koolex

high

# offerBorrowAmountLowerBound (alone) doesn't mitigate the ddos risk for all ERC20 tokens effectively

## Summary
 **offerBorrowAmountLowerBound** (alone) doesn't mitigate the ddos risk for all ERC20 tokens effectively.

## Vulnerability Detail
The protocol allows any ERC20 token which makes it impractical to protect all lenders by setting offerBorrowAmountLowerBound for all tokens.
Moreever, there are tokens that have two addresses (e.g. Synthetix's ProxyERC20 contract that exists in multiple forms such as sBTC, sUSD ...etc). If some lenders use the other address of the token in an offer, then a borrower could use this offer and bypass the offerBorrowAmountLowerBound that was set for the main address. Please read the impact below for a clearer picture.

## Impact
According to the comments in `BorrowCheckers.checkOfferArg` method
> This bound set by governance is used as an anti-ddos measure to prevent borrowers to spam the creation of supply positions not worth to claim by lenders from a gas cost perspective after a liquidation

This means, it is the responsibility of the governance to set this bound, and the protocol accepts the risk if the governance has not set it to a sufficient value.
> Borrowers can effectively lock lenders funds by spaming the minting of supply positions on ERC20s where the governance has not set a minOfferCost or an offerBorrowAmountLowerBound at sufficient values.

However, since the protocol allows any ERC20 token, the governance is likely to overlook (or even be not aware of) a token that has two addresses. Thus, having the offerBorrowAmountLowerBound unset (i.e. equals zero) for some tokens which ultimately makes the anti-ddos measure (mentioned above) ineffective. Morever, as the protocol allows any ERC20 token, it's almost impossible to protect all lenders since there are tons of tokens and it's impractical to contain all of it.

## Code Snippet
```sh
        /* we use a lower bound, I.e the actual amount must be strictly higher that this bound as a way to prevent a 0 
        amount to be used even in the case of an uninitialized parameter for a given erc20. This bound set by governance
        is used as an anti-ddos measure to prevent borrowers to spam the creation of supply positions not worth to claim
        by lenders from a gas cost perspective after a liquidation. more info in docs */
        uint256 amountLowerBound = proto.offerBorrowAmountLowerBound[arg.offer.assetToLend];

        if (!(arg.amount > amountLowerBound)) {
            revert RequestedAmountIsUnderMinimum(arg.offer, arg.amount, amountLowerBound);
        }

```
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowCheckers.sol#L31-L39

## Tool used

Manual Review

## Recommendation

Consider adding an allow list of accepted ERC20 tokens, add the acceptable tokens to the list, and revert on borrowing if the token is not allowed. 
This way, the governance can add the token addresses that they are aware of. In case, a token isn't allowed, then such a risk (described above) would be mitigated. 
Additionally, it's less likely that the governance forget to set offerBorrowAmountLowerBound for a particular token.

**Comment by npasquie** [comment]
The admin overlooking a token existing in two addresses would be an admin mistake, which is out of scope
Even in this case, lender offers can be signed with the token address with threshold set, and the protection is effective

**Comment by koolexcrypto** [comment]
Escalate for 10 USDC

I disagree with that because admin mistakes is in-scope.
The protocol doesn't explicitly mention admin mistakes are known issues in the contest page.
Not only overlooking it but possibly not being aware of it having a second address.

**Comment by hrishibhat** [comment]
Escalation rejected

Admin is trusted and admin input validation is a not a valid high/medium
