### ISSUE TITLE
amaechieth - Lenders can permanently lose their loan value

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#40]
amaechieth

high

# Lenders can permanently lose their loan value

## Summary

`borrow` in `BorrowFacet.sol` will succeed even if the NFT collateral is not transferred to escrow, causing the lender to lose their ERC20 loan. A malicious borrower can incentivise an unaware lender to use this protocol to securely lend their tokens using a malicious NFT.

## Vulnerability Detail

The `borrow` function transfers the collateral NFT to the `BorrowFacet.sol` contract using IERC721 `transferFrom` rather than `safeTransferFrom`. Also, the success of this transfer is not checked. 

There are ERC721 tokens that return false instead of revert. 

The lack of transfer success checks gives the lender no protection for failed transfers & potentially allows a malicious user to steal from lenders using malicious ERC721 contracts.

A malicious user `Bob` can incentivise an unsuspecting user `Alice` to use Kairos protocol to securely lend collateral for a specific NFT. Alice reviews the terms of Kairos and believes this is a secure way to loan collateral for tokens & accepts the risk that the user may not repay their loan, however, acknowledges the NFT will be put for auction so accepts on this basis.

Bob's NFT is a malicious one which reverts on all transfers, so the NFT is not held in the protocols escrow, however, Bob has still been given Alice's ERC20 tokens. This case can be avoided if the protocol ensures the NFT is in escrow before Alice tokens are transferred to the user. Alice's responsibility is due diligence for the NFT she wants to allow to be used as collateral, but in this case, the NFT never reaches escrow which is the responsibility of the protocol as this can easily be avoided by a simple transfer success check.

```solidity
function borrow(BorrowArg[] calldata args) external { 
        for (uint256 i = 0; i < args.length; i++) {
            args[i].nft.implem.transferFrom(msg.sender, address(this), args[i].nft.id);
            useCollateral(args[i].args, msg.sender, args[i].nft); 
        }
    }
```

```solidity
struct BorrowArg {
    NFToken nft;
    OfferArg[] args;
}
```

```solidity
struct NFToken {
    IERC721 implem;
    uint256 id;
}
```

## Impact

Lenders have no protection from being rug-pulled by malicious NFTs or NFTs which return a bool instead of revert on failed transfers.

## Code Snippet

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowFacet.sol#L38-L43

If a contract returns a boolean based on transfer success, the current implementation will not catch failed transfers:

```solidity
function transferFrom(address from, address to, uint256 tokenId) public returns (bool) {
        
        // Logic goes here
        
        // Returns false if conditions are not met
        return false;
    }
```

## Tool used

Manual Review

## Recommendation

Add a check to ensure the `transferFrom` was successful.

**Comment by npasquie** [comment]
The [erc721 standard](https://eips.ethereum.org/EIPS/eip-721) specifies that `transferFrom()` implementations must not return anything
It is the responsibility of lenders not to rug themselves by signing offers for malicious collaterals
