### ISSUE TITLE
MalfurionWhitehat - Lack of offer expiration control

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#45]
MalfurionWhitehat

medium

# Lack of offer expiration control

## Summary

The typeHashOffer function in the provided Solidity smart contract lacks a mechanism for lenders to expire their offers beyond the expirationDate parameter. 

## Vulnerability Detail

The typeHashOffer function in the provided Solidity smart contract lacks a mechanism for lenders to expire their offers beyond the expirationDate parameter. The absence of such a feature can lead to various issues, such as market conditions changing suddenly or a depegging event. As a result, lenders may want to expire all active offers, which is currently not possible.

## Impact

The inability to expire all active offers can lead to significant risks for the lender. In the absence of a nonce mapping, they would be unable to control the expiration of their offers in response to changing market conditions. This can result in lenders experiencing significant losses and damage to their reputation.

## Code Snippet

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/Signature.sol#L41-L54

## Tool used

Manual Review

## Recommendation

Add a nonce mapping for offers so that lenders can manage their offers effectively and mitigate risks associated with market volatility.

**Comment by npasquie** [comment]
similar to #75
there I said "as mentioned in docs, the expirationDate and revoking token approvals are the intended ways of making offers unavailable"
