### ISSUE TITLE
zaevlad - DDOS risk if a borrower spams the use of offers with small amounts

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#55]
zaevlad

high

# DDOS risk if a borrower spams the use of offers with small amounts

## Summary

Despite the system checks with minOfferCost and offerBorrowAmountLowerBound managed by administration there is a risk of ddos with new assets (ERC20) that appear in the protocol.

## Vulnerability Detail

There are several comments in the contracts that describes a vulnarability with ddos risk and how a team goint to prevent it. Here is an example that can be found in BorrowHandlers.sol:

> "The minimum interests amount to repay is used as anti ddos mechanism to prevent borrowers to produce lots of dust supply positions that the lenders will have to pay gas to claim. This is why it is determined on a per-offer basis, as each position can be used to claim funds separetely and induce a gas cost..."

That paramert is based on minOfferCost:

`notPaid.minInterestsToRepay = nbOfOffers * proto.minOfferCost[collatState.assetLent];`

minOfferCost and offerBorrowAmountLowerBound are protocol settings that can be found in mapping in Protocol struct.

**The problem rises** if administration will skip for any reason adding a new ERC20 asset in these mappings and a user create an offer. 

In that case when another user will borrow a loan for his NFT, the check: 

`notPaid.minInterestsToRepay = nbOfOffers * proto.minOfferCost[collatState.assetLent];`

will return zero (0), because if there is no such key in the mapping it will return default value, 0 is for the uint256.

With such vulnarability a malicious user can spam the protocol.

## Impact

Borrowers can produce lots of dust supply positions that the lenders will have to pay gas to claim. I.e this spam would let the lender with many dust positions to claim onchain, which may be not financially viable due to gas costs

## Code Snippet

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/DataStructure/Storage.sol#L33
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L64
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L72
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L180

## Tool used

Manual Review

## Recommendation

Follow up for any new assets that appear in the protocol or create a ERC20 whitelist to be up to date with any assets.

**Comment by zaevlad** [comment]
Escalate for 10 USDC

I think this is wrongly Excluded. Developers several times stated that problem in the docs and contract comments, but DDOS of dust supply position is still exists with the new ERC20 assets.

**Comment by hrishibhat** [comment]
Escalation rejected

> if administration will skip for any reason adding a new ERC20 asset in these mappings and a user create an offer.
This is an admin input validation. This issue is not a valid high/medium issue.
