### ISSUE TITLE
GimelSec - If a tranche is stale or inappropriate, it cannot be removed from the protocol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#65]
GimelSec

medium

# If a tranche is stale or inappropriate, it cannot be removed from the protocol

## Summary

The admin of protocol can add a new tranche for lenders to provide offers for. But the admin cannot remove the added tranches. If there is a tranche that is stale or inappropriate, it is impossible to remove it from the protocol.

## Vulnerability Detail

The admin of protocol can add a new tranche for lenders to provide offers for.
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L47
```solidity
    /// @notice creates a new tranche at a new identifier for lenders to provide offers for
    /// @param newTranche the interest rate of the new tranche
    function createTranche(Ray newTranche) external onlyOwner returns (uint256 newTrancheId) {
        Protocol storage proto = protocolStorage();

        newTrancheId = proto.nbOfTranches++;
        proto.tranche[newTrancheId] = newTranche;

        emit NewTranche(newTranche, newTrancheId);
    }
```

Lenders can choose the desired tranches in their offers. If there is a bad tranche in favor of lenders. The lenders are intended to choose that tranche. And the protocol cannot remove it.

## Impact

If there is a bad tranche. the admin cannot remove it from the protocol.

## Code Snippet

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/AdminFacet.sol#L47

## Tool used

Manual Review

## Recommendation

Add a mechanism to remove bad tranches.

**Comment by npasquie** [comment]
The admin making a mistake creating a tranche is out of scope
