### ISSUE TITLE
GimelSec - `ClaimFacet.sendShareOfSaleAsSupplier()` calculates unfair shares, the money should compensate lenders first.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#72]
GimelSec

high

# `ClaimFacet.sendShareOfSaleAsSupplier()` calculates unfair shares, the money should compensate lenders first.

## Summary

`ClaimFacet.sendShareOfSaleAsSupplier()` calculates unfair shares, the money should compensate lenders first.

## Vulnerability Detail

Suppose a NFT token values 200 USDC, and Eve calls `borrow`.
* loanToValue of Alice's loan is 100 USDC, Eve borrows 10 USDC, provision.share: 10%
* loanToValue of Bob's loan is 200 USDC, Eve borrows 10 USDC, provision.share: 5%

Someone liquidates, if the paid amount is less than `loan.lent`, for example, 15 USDC. Then:
* Alice will get 1.5 USDC due to `15 * 10%`
* Bob will get 0.75 USDC due to `15 * 5%`
* Eve (borrower) will get 12.75 USDC, but these tokens should compensate lenders first.

For example:
* Alice will get 10 USDC due to `15 * (10% / (10% + 5%))`
* Bob will get 5 USDC due to `15 * (5% / (10% + 5%))`
* Eve (borrower) will get 0 USDC

## Impact

The lenders will lose funds, the paid amount should compensate lenders first.

## Code Snippet

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/ClaimFacet.sol#L117

## Tool used

Manual Review

## Recommendation

The paid amount should not be sent to the borrower if `loan.payment.paid` doesn't have enough money.

```solidity
    function claimAsBorrower(uint256[] calldata loanIds) external returns (uint256 sent) {
        ...
            if (loan.payment.liquidated) {
                loan.payment.borrowerClaimed = true;
                sentTemp = loan.payment.paid.mul(ONE.sub(loan.shareLent));
+               if (loan.payment.paid < loan.lent) {
+                   sentTemp = 0;
+               }
            } else {
                revert LoanNotRepaidOrLiquidatedYet(loanId);
            }
        ...
    }

    function sendShareOfSaleAsSupplier(
        Loan storage loan,
        Provision storage provision
    ) internal returns (uint256 sent) {
        if (loan.payment.paid < loan.lent) {
            sent = loan.payment.paid.mul(provision.share).div(loan.shareLent);
        } else {
            sent = loan.payment.paid.mul(provision.share);
        }
        loan.assetLent.checkedTransfer(msg.sender, sent);
    }
```

Duplicate of #110

**Comment by npasquie** [comment]
This report is similar to #110 
I consider it invalid, referring to the same design rationale of lender claims
Lenders are estimating a price under which they think the fair value of the NFT won't fall, depending on the accuracy of this estimation, lenders will (and should) gain or lose from the operation
The borrower has the ability to borrow less than the maximum as a way to retain ownership on some of the NFT value, which should not be taken and given to lenders without having borrowed the corresponding amount

**Comment by npasquie** [comment]
similar to #110
