### ISSUE TITLE
ck - Reentrancy risk in the `BorrowFacet::borrow` function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#74]
ck

high

# Reentrancy risk in the `BorrowFacet::borrow` function

## Summary

Reentrancy risk in the `BorrowFacet::borrow` function

## Vulnerability Detail

The `BorrowFacet::borrow`  calls `BorrowHandlers::useCollateral` which in turn calls `BorrowHandlers::useOffer`
The `BorrowHandlers::useOffer` mints an NFT to the signer of the loan:

```solidity
        // issuing supply position NFT to the signer of the loan offer with metadatas
        safeMint(signer, Provision({amount: arg.amount, share: shareMatched, loanId: collatState.loanId}));
        return (collatState);
```

After this `BorrowHandlers::useCollateral` initializes the loan and updates protocol storage.

```solidity
        loan = initializedLoan(collatState, from, nft, nbOfOffers, lent, firstSupplyPositionId);
        protocolStorage().loan[collatState.loanId] = loan;
```

The issue is that the signer/lender of the loan could implement an `onERC721Received` so that when an NFT is minted to them, they themselves initate a new borrow before the initial borrower's loan is initialzed and protocol storage updated.

When the execution flow continues for the initial borrower, various loan parameters will have changed which will result in their loan initialization containing modified values from the reentrancy.

## Impact

Borrowers could be made to have loans initialized with a higher lent value than the amount of tokens they actually borrowed.

## Code Snippet

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowFacet.sol#L38-L42

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L100-L126

https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L87-L92

## Tool used

Manual Review

## Recommendation

Initialize the loan and update the protocol before minting the NFT to the signer/lender.

**Comment by npasquie** [comment]
the lent amount stored in loan is a memory value stored after external calls and is unaffected by reentrencies
