### ISSUE TITLE
Inspex - Lack of Loan Offer Management

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#75]
Inspex

high

# Lack of Loan Offer Management

## Summary
The lender signs a loan offer that specifies the `loanToValue` amount for the NFT that can be used as collateral. However, if the lender mistakenly inputs the wrong value in an offer or if the NFT price has dropped, they cannot revoke the offer due to the platform lacking a mechanism to do so.

## Vulnerability Detail
An attacker as a borrower could take any loan offer that appears profitable to them. Although the `BorrowCheckers` contract checks for the expiration date, there is no implementation for validate or managing the loan offers that lenders want to cancel.

## Impact
A non-cancellable loan offer poses several risks, including the possibility of a price dump of the collateral NFT, and attacker can use that NFT to borrow for more than value of it, Additionally, an unexpected change to the platform could result in the loss of benefits with the loan offer.

## Code Snippet
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowCheckers.sol#L17

## Tool used

Manual Review

## Recommendation
We recommend implementing a loan offer revoke feature that enables lenders to cancel offers as needed.

Duplicate of #45

**Comment by npasquie** [comment]
as mentioned in docs, the expirationDate and revoking token approvals are the intended ways of making offers unavailable

**Comment by npasquie** [comment]
similar to #45
