### ISSUE TITLE
evo - A borrower will not be able to repay if the collateral is evolved NFT

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#90]
evo

medium

# A borrower will not be able to repay if the collateral is evolved NFT

## Summary
Some of the NFTs of ERC721 contracts might be paused or evolved by their owners or projects governance and will disable the ability to return the NFT because there is no way to repay since the NFT affected by its collection contract.

## Vulnerability Detail
Imagine you have NFT as collateral and you used a loan for it and now it is on Kairos custody (Contract) but this one (The NFT) has the ability to be evolved after a while and as an action by the project's owners it will has new collection address after evolvement.

In this case the repay method by the Borrower it will fail as well because the Collateral now had different collection address. Now the Borrower lost the ability to repay and lost his NFT. Also when it goes to auction, no one can buy it as the loan collateral token doesn't exist any more.

simple scenario:
- Alex find an interesting NFT that has the possibility to evolve.
- Bob as borrower borrows a `loanToValue` from Alex's offer
- The collateral NFT of Bob will be in Kairos contract's custody.
- The NFT becomes evolved (burned and converted to new token).
- Now the protocol will not recognize the new collection address of evolved token and consider the token does not exist.
- Bob has no way to repay Alex.
- Alex loses his chance to get his `loanToValue` back from Bob. 

## Impact
A total fail when a Borrower would need to repay his loan to get his collateral NFT back and eventually he loses the chance to repay the loan. and the Lender loses his money where there is no NFT going to auction.
<br/>

## Code Snippet
https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/RepayFacet.sol#L58
` loan.collateral.implem.safeTransferFrom(address(this), loan.borrower, loan.collateral.id);`

## Tool used
Manual Review
<br/>

## Recommendation
Offer a chance to Borrower to repay his loan if something happened to the Collateral NFT for no reason.

**Comment by npasquie** [comment]
Tokens behaving in a non standard way can't be considered to be the responsibility of the protocol using them, it is the responsibility of toke admins to update their systems in safe ways, and of users not to use tokens with arbitrary behavior
